#ifndef KOTLIN_COMPILER_SEMANTICERRORCODE_H
#define KOTLIN_COMPILER_SEMANTICERRORCODE_H


enum SemanticErrorCode {
    EMPTY_AST_TREE = 1000,

    REDEFINITION = 1001,
    UNDEFINED_CLASS = 1002,
    INVALID_INHERITANCE = 1003,
    FINAL_CLASS_INHERITANCE = 1004,
    METHOD_ALREADY_EXISTS = 1005,
    CLASS_ALREADY_EXISTS = 1006,
    TOP_LEVEL_METHOD_WITH_THIS_NAME_ALREADY_EXIST = 1007,
    CONSTRUCTOR_ALREADY_EXISTS = 1008,
    MISSING_RETURN_VALUE = 1009,
    RETURN_FROM_VOID = 1010,
    RETURN_TYPE_MISMATCH = 1011,
    UNALLOWED_ASSIGNMENT_CONTEXT = 1012,
    UNDEFINED_VARIABLE = 1013,
    UNINITIALIZED_VARIABLE = 1014,
    VAL_REASSIGNMENT = 1015,
    ASSIGNMENT_TYPES_MISMATCH = 1016,
    INVALID_ARRAY_ASSIGNMENT = 1017,
    UNDEFINED_ARRAY_ELEMENTS_TYPE = 1029,
};


#endif //KOTLIN_COMPILER_SEMANTICERRORCODE_H