#ifndef KOTLIN_COMPILER_SEMANTICERRORCODE_H
#define KOTLIN_COMPILER_SEMANTICERRORCODE_H


enum SemanticErrorCode {
    EMPTY_AST_TREE = 1000,

    REDEFINITION = 1001,
    UNDEFINED_CLASS = 1002,
    INVALID_INHERITANCE = 1003,
    FINAL_CLASS_INHERITANCE = 1004,
    METHOD_ALREADY_EXISTS = 1005,
    CLASS_ALREADY_EXISTS = 1006,
    TOP_LEVEL_METHOD_WITH_THIS_NAME_ALREADY_EXIST = 1007,
    CONSTRUCTOR_ALREADY_EXISTS = 1008,
    MISSING_RETURN_VALUE = 1009,
    RETURN_FROM_VOID = 1010,
    RETURN_TYPE_MISMATCH = 1011,
    UNALLOWED_ASSIGNMENT_CONTEXT = 1012,
    UNDEFINED_VARIABLE = 1013,
    UNINITIALIZED_VARIABLE = 1014,
    VAL_REASSIGNMENT = 1015,
    ASSIGNMENT_TYPES_MISMATCH = 1016,
    INVALID_ARRAY_ASSIGNMENT = 1017,
    MULTIVAR_FOR_LOOP = 1018,               // многопеременный for
    FOR_LOOP_NOT_ARRAY = 1019,              // for работает только с массивами
    CONDITION_NOT_BOOLEAN = 1020,           // if/while условие не Boolean
    BREAK_OUTSIDE_LOOP = 1021,              // break вне цикла
    CONTINUE_OUTSIDE_LOOP = 1022,           // continue вне цикла
    UNEXPECTED_RETURN = 1023,               // return в неожидаемом месте
    FUNCTION_ALREADY_EXISTS = 1024,         // функция с таким именем уже существует
    FIELD_ALREADY_EXISTS = 1025,            // поле с таким именем уже существует
    INVALID_CAST = 1026,                    // недопустимое приведение типов
    NULL_POINTER_ACCESS = 1027,             // обращение к null
    INVALID_OPERATOR = 1028,                // оператор применён к несовместимым типам
    UNDEFINED_ARRAY_ELEMENTS_TYPE = 1029,
    CLASS_NOT_FOUND = 1030,
    METHOD_NOT_FOUND = 1031,
    METHOD_CANDIDATE_NOT_FOUND = 1032,
    NULL_SEMANTIC_TYPE_FOR_LEFT_EXPR = 1033,
    NULL_SEMANTIC_TYPE = 1034,
    NOT_REPLACEABLE_TYPES = 1035,
    UNDECLARED_TYPE = 1036,
    DIFFERENT_TYPES_IN_ARRAY_CREATION = 1037,
    EMPTY_RANGE = 1038,
    INVALID_RANGE_TYPE = 1039,
    INVALID_RANGE_PARAMS = 1040,
    INVALID_STEP_VALUE = 1041,
    INVALID_ITERATOR_TYPE = 1042,
    NOT_IDENTIFIER_IN_ARRAY_ACCESS = 1043,
    NOT_INT_INDEX_TYPE = 1044,
    INVALID_FIELD_TYPE = 1045,
    FIELD_NOT_INITIALIZED = 1046,
    INVALID_TOP_LEVEL_FUNCTION_MODIFIER = 1047,
    SUPER_CLASS_DOES_NOT_EXIST = 1048,
    INHERITANCE_FROM_FINAL_CLASS = 1049,
    INVALID_MODIFIER_COMBINATION_PRIVATE_OPEN = 1056,
    INCOMPATIBLE_MODIFIERS = 1057,
    UNEXPECTED_TOKEN_AFTER_TOP_LEVEL_KEYWORD = 1058,
};


#endif //KOTLIN_COMPILER_SEMANTICERRORCODE_H